# yaml-language-server: $schema=../schemas/issues.schema.json

issues:
  - key: 'setup'
    title: '🚀 [setup] Project Setup Foundation'
    milestone: '🚀 Project Setup'
    labels:
      - 'type:feature'
      - 'scope:core'
      - 'scope:workflow'
      - 'priority:high'
    dependencies: []
    description: |
      ### Short Description
      Establish the baseline folder structure, core utilities, shared schemas, and initial workflow templates.

      ### Goal
      Build a stable and typed foundation for all subsequent automation modules.

      ### Subtasks
      - Create `/src`, `/workflows`, `/templates`, `/schemas`, `/scripts`
      - Implement GitHub API core utilities (Octokit wrappers)
      - Add hashing utility for sync comparisons
      - Add YAML/JSON schema validation utilities
      - Create initial reusable workflow templates

      ### Outcomes
      - Repository infrastructure ready
      - Shared utilities usable across sync systems
      - CI pipeline validates schemas & builds scripts

  - key: 'ms-sync'
    title: '🧩 [milestones] Milestones Sync System'
    milestone: '🧩 Milestones Sync'
    labels:
      - 'type:feature'
      - 'scope:milestones'
      - 'priority:high'
    dependencies:
      - 'setup'
    description: |
      ### Short Description
      Implement milestone parsing, hashing, and GitHub synchronization logic.

      ### Goal
      Make milestones fully declarative with auto-creation, updating, and conflict detection.

      ### Subtasks
      - Parse milestone YAML (file or folder)
      - Extract key from square brackets in title
      - Create/update/delete milestones based on diffing
      - Calculate new/old GitHub hash to detect changes
      - Write back numbers & hashes to YAML
      - Add GitHub summary diffs and skipped table
      - Implement merge-conflict comments into YAML when GitHub differs

      ### Outcomes
      - Complete IAC-based milestone governance
      - Accurate diff-based updates
      - Change-safe syncing with conflict protection

  - key: 'label-sync'
    title: '🏷️ [labels] Label Sync System'
    milestone: '🏷️ Labels Sync'
    labels:
      - 'type:feature'
      - 'scope:labels'
      - 'priority:medium'
    dependencies:
      - 'setup'
    description: |
      ### Short Description
      Implement YAML-driven label definitions and synchronization workflow.

      ### Goal
      Ensure labels are fully declarative, grouped, and consistently applied across the repo.

      ### Subtasks
      - Parse label YAML file
      - Create/update/delete labels on GitHub
      - Support grouped categories (priority, type, scope)
      - Produce diff summary and skipped table
      - Ensure stable color & description updates

      ### Outcomes
      - Labels fully controlled via YAML
      - Clean, predictable taxonomy for CI, epics, milestones

  - key: 'issue-sync'
    title: '📦 [issues] Issue & Epic Sync System'
    milestone: '📦 Issues Sync'
    labels:
      - 'type:feature'
      - 'scope:issues'
      - 'priority:high'
    dependencies:
      - 'setup'
      - 'ms-sync'
      - 'label-sync'
    description: |
      ### Short Description
      Build the declarative issue/epic creation and update system, including dependencies and label/milestone synchronization.

      ### Goal
      Represent epics, tasks, and sub-issues in YAML and sync them safely to GitHub.

      ### Subtasks
      - Parse issue definitions (epics + subtasks)
      - Apply prefix key for stable identity
      - Sync labels, milestones, dependencies
      - Detect differences using hash comparison
      - Write back updated data to YAML
      - Provide GitHub summary with diff indicators

      ### Outcomes
      - Declarative issue management
      - Reproducible epics and hierarchical structures
      - Diff-driven updates with no accidental overrides

  - key: 'project-sync'
    title: '📊 [projects] GitHub Projects Sync System'
    milestone: '📊 Project Sync'
    labels:
      - 'type:feature'
      - 'scope:projects'
      - 'priority:medium'
    dependencies:
      - 'setup'
    description: |
      ### Short Description
      Implement declarative GitHub Projects (Classic and V2) synchronization.

      ### Goal
      Automatically configure columns, status fields, descriptions, and settings based on YAML.

      ### Subtasks
      - Parse project definitions from file or folder
      - Detect classic vs V2 by project number
      - Sync description, columns, fields, views
      - Show diffs in GitHub summary
      - Support multi-project and cross-repo layouts

      ### Outcomes
      - Fully automated project structure
      - Consistent fields across workflows
      - Reusable IAC-style project configuration

  - key: 'pipeline'
    title: '🔁 [pipeline] Full Automation Pipeline'
    milestone: '🔁 Full Automation Pipeline'
    labels:
      - 'type:enhancement'
      - 'scope:workflow'
      - 'scope:core'
      - 'priority:medium'
    dependencies:
      - 'ms-sync'
      - 'label-sync'
      - 'issue-sync'
      - 'project-sync'
    description: |
      ### Short Description
      Combine all sync systems into one orchestrated workflow with shared utilities.

      ### Goal
      Provide a unified end-to-end automation execution via GitHub Actions or CLI.

      ### Subtasks
      - Create composite workflows combining sync steps
      - Add CLI entrypoint to run partial or full sync
      - Add cross-system hashing to avoid unnecessary work
      - Add unified GitHub summary with all diffs
      - Allow user to choose modules via input

      ### Outcomes
      - One-command full automation
      - Reusable across repositories
      - Minimal manual maintenance
