# yaml-language-server: $schema=../schemas/labels.schema.json

labels:
  # PRIORITY
  - name: 'priority:critical'
    color: 'd73a4a'
    description: 'Must be fixed immediately. Blocks releases.'

  - name: 'priority:high'
    color: 'ff6f59'
    description: 'Should be worked on soon; blocks major features.'

  - name: 'priority:medium'
    color: 'fbca04'
    description: 'Normal importance tasks.'

  - name: 'priority:low'
    color: 'c2e0c6'
    description: 'Nice-to-have, no urgency.'

  # TYPE
  - name: 'type:feature'
    color: '0e8a16'
    description: 'New functionality for automation tools.'

  - name: 'type:enhancement'
    color: '84b6eb'
    description: 'Improvements to existing workflows.'

  - name: 'type:bug'
    color: 'd73a4a'
    description: 'Incorrect or failing behavior.'

  - name: 'type:refactor'
    color: 'c5def5'
    description: 'Internal code-level improvement.'

  - name: 'type:docs'
    color: '006b75'
    description: 'Documentation or README updates.'

  - name: 'type:chore'
    color: 'ededed'
    description: 'Maintenance, CI updates, or dependency updates.'

  - name: 'type:breaking'
    color: '5319e7'
    description: 'Changes requiring workflow migration.'

  # SCOPE
  - name: 'scope:milestones'
    color: '5319e7'
    description: 'Milestone sync scripts & workflow.'

  - name: 'scope:labels'
    color: '1d76db'
    description: 'Label sync system.'

  - name: 'scope:issues'
    color: '006b75'
    description: 'Issue sync scripts.'

  - name: 'scope:projects'
    color: '0e8a16'
    description: 'GitHub Projects sync automation.'

  - name: 'scope:schemas'
    color: 'fbca04'
    description: 'Zod/JSON/YAML schema definitions.'

  - name: 'scope:workflow'
    color: 'b60205'
    description: 'GitHub workflow logic & reusable templates.'

  - name: 'scope:cli'
    color: 'fde3e3'
    description: 'CLI tool and npx interface.'

  - name: 'scope:core'
    color: 'c2e0c6'
    description: 'Shared utilities, GitHub API, loaders, hashing.'
